version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: icvvtv_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - icvvtv_network

  mongo-express:
    image: mongo-express:latest
    container_name: icvvtv_mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - icvvtv_network

volumes:
  mongodb_data:

networks:
  icvvtv_network:
    driver: bridge 